{
 "title": "Health",
 "time": { "from": "now-3h", "to": "now-10s" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "bucket",
    "label": "Bucket",
    "query": "adventureland, adventureland-debug"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"state\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"inv_slots_free\")\r\n  |> group(columns: [\"character\"])\r\n  |> aggregateWindow(every: $__interval, fn: max)\r\n  |> keep(columns: [\"_time\", \"_value\", \"character\"])\r\n  "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"state_bank\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"bank_slots_free\")\r\n  |> aggregateWindow(every: $__interval, fn: max)\r\n  |> fill(usePrevious: true)\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kill\")\r\n  |> filter(fn: (r) => \r\n      r[\"npc_type\"] == \"crab\" or \r\n      r[\"npc_type\"] == \"phoenix\" or \r\n      r[\"npc_type\"] == \"squig\" or \r\n      r[\"npc_type\"] == \"mvampire\" or \r\n      r[\"npc_type\"] == \"rgoo\" or\r\n      r[\"npc_type\"] == \"bgoo\" or \r\n      r[\"npc_type\"] == \"goldenbat\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"npc_type\"])\r\n  |> map(fn: (r) => ({ r with _value: 1 }))\r\n  |> group(columns: [\"npc_type\"])\r\n  |> aggregateWindow(every: $__interval, fn: count)\r\n\r\n\r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tick_rate\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"avg\")\r\n  |> group(columns: [\"character\", \"_field\"])\r\n  |> keep(columns: [\"_time\", \"_value\", \"character\"])\r\n  |> aggregateWindow(every: $__interval, fn: mean)\r\n  |> map(fn: (r) => ({ r with _value: 1000.0 / r._value }))\r\n\r\n  "
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"health_percent\")\r\n  |> group(columns: [\"character\"])\r\n  |> aggregateWindow(every: $__interval, fn: mean)\r\n\r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"mana_percent\")\r\n  |> group(columns: [\"character\"])\r\n  |> aggregateWindow(every: $__interval, fn: mean)\r\n\r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 2 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kill\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"npc_type\"])\r\n  |> map(fn: (r) => ({ r with _value: 1 }))\r\n  |> group(columns: [\"npc_type\"])\r\n  |> aggregateWindow(every: $__interval, fn: count)\r\n  \r\n"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket:\"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"cpu\" and (r._field == \"usage_system\" or r._field == \"usage_user\") and r.cpu == \"cpu-total\")\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> aggregateWindow(every: $__interval, fn: max)\r\n"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 2, "x": 19, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket:\"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mem\" and (r._field == \"active\" or r._field == \"available\"))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> aggregateWindow(every: $__interval, fn: max)\r\n  "
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket:\"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"disk\" and (r._field == \"used\" or r._field == \"free\") and r.device == \"md3\")\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> group(columns: [\"_field\"])\r\n  |> aggregateWindow(every: $__interval, fn: max)\r\n"
    }
   ]
  },
  {
   "title": "Frames",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"tick_rate\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"min\" or r[\"_field\"] == \"avg\" or r[\"_field\"] == \"max\")\r\n  |> group(columns: [\"character\", \"_field\"])\r\n  |> keep(columns: [\"_time\", \"_value\", \"character\", \"_field\"])\r\n  |> aggregateWindow(every: $__interval, fn: max)\r\n\r\n  "
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"state\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"xp\")\r\n  |> group(columns: [\"character\"])\r\n  |> aggregateWindow(every: $__interval, fn: mean)\r\n  |> difference()\r\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"state\")\r\n  |> filter(fn: (r) => r[\"character\"] == \"Arcanomato\")\r\n  |> map(fn: (r) => ({ _time: r._time, _value: r.map }))\r\n  |> duplicate(column: \"_value\", as: \"map\")\r\n  |> group(columns: [\"map\"])\r\n  |> count()\r\n  |> group()\r\n\r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 7 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"damage\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hit\")\r\n  |> filter(fn: (r) => r[\"character\"] == \"Arcanomato\")\r\n  |> filter(fn: (r) => r[\"source\"] != \"burn\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: $__interval, fn: count, createEmpty: true)\r\n  \r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kill\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"luck_chance\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"npc_type\"])\r\n  |> group(columns: [\"npc_type\"])\r\n  |> aggregateWindow(every: $__interval, fn: mean)\r\n  \r\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"state\")\r\n  |> filter(fn: (r) => r[\"character\"] == \"Arrowmato\")\r\n  |> map(fn: (r) => ({ _time: r._time, _value: r.map }))\r\n  |> duplicate(column: \"_value\", as: \"map\")\r\n  |> group(columns: [\"map\"])\r\n  |> count()\r\n  |> group()\r\n\r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"damage\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hit\")\r\n  |> filter(fn: (r) => r[\"character\"] == \"Arrowmato\")\r\n  |> filter(fn: (r) => r[\"source\"] != \"burn\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: $__interval, fn: count, createEmpty: true)\r\n  \r\n"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kill\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> keep(columns: [\"_time\", \"npc_type\"])\r\n  |> map(fn: (r) => ({ r with _value: 1 }))\r\n  |> group(columns: [\"npc_type\"])\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: true)\r\n  |> fill(value: 0)\r\n  |> mean()\r\n  |> group()\r\n  |> sort(desc: true)\r\n"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"kill\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"luck_chance\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"npc_type\"])\r\n  |> group(columns: [\"npc_type\"])\r\n  |> aggregateWindow(every: 1m, fn: mean)\r\n\r\n  \r\n"
    }
   ]
  },
  {
   "title": "Net (latency)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"ping\")\r\n  |> group(columns: [\"character\"])\r\n  |> aggregateWindow(every: $__interval, fn: max)\r\n  |> keep(columns: [\"_time\", \"_value\", \"character\"])"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"state\")\r\n  |> filter(fn: (r) => r[\"character\"] == \"Ragemato\")\r\n  |> map(fn: (r) => ({ _time: r._time, _value: r.map }))\r\n  |> duplicate(column: \"_value\", as: \"map\")\r\n  |> group(columns: [\"map\"])\r\n  |> count()\r\n  |> group()\r\n\r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 13 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"damage\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hit\")\r\n  |> filter(fn: (r) => r[\"character\"] == \"Ragemato\")\r\n  |> filter(fn: (r) => r[\"source\"] != \"burn\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: $__interval, fn: count, createEmpty: true)\r\n  \r\n"
    }
   ]
  },
  {
   "title": "Net (recv) per 10s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"direction\"] == \"incoming\")\r\n  |> group(columns: [\"event\"])\r\n  |> aggregateWindow(every: $__interval, fn: mean)\r\n"
    }
   ]
  },
  {
   "title": "Net (sent) per 10s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"net\")\r\n  |> filter(fn: (r) => r[\"direction\"] == \"outgoing\")\r\n  |> group(columns: [\"event\"])\r\n  |> aggregateWindow(every: $__interval, fn: mean)\r\n"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"state\")\r\n  |> filter(fn: (r) => r[\"character\"] == \"Seamato\")\r\n  |> map(fn: (r) => ({ _time: r._time, _value: r.map }))\r\n  |> duplicate(column: \"_value\", as: \"map\")\r\n  |> group(columns: [\"map\"])\r\n  |> count()\r\n  |> group()\r\n\r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 6, "x": 2, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"damage\")\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hit\")\r\n  |> filter(fn: (r) => r[\"character\"] == \"Seamato\")\r\n  |> filter(fn: (r) => r[\"source\"] != \"burn\")\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: $__interval, fn: count, createEmpty: true)\r\n  \r\n"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"state\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"cc\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"character\"])\r\n  |> group(columns: [\"character\"])\r\n  |> aggregateWindow(every: $__interval, fn: max)\r\n"
    }
   ]
  },
  {
   "title": "Damage per $__interval",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 20 },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hit\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"damage\")\r\n  |> group(columns: [\"character\"])\r\n  |> aggregateWindow(every: $__interval, fn: sum, createEmpty: true)\r\n  |> fill(value: 0.0)\r\n\r\n"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hit\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"damage\")\r\n  |> group(columns: [\"character\"])\r\n  |> aggregateWindow(every: 1s, fn: sum, createEmpty: true)\r\n  |> fill(value: 0.0)\r\n  |> mean()\r\n  |> keep(columns: [\"_time\", \"_value\", \"character\"])\r\n  |> rename(columns: {_value: \"Avg DPS\"})\r\n"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${bucket}\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"hit\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"damage\")\r\n  |> group(columns: [\"character\"])\r\n  |> aggregateWindow(every: 1s, fn: sum, createEmpty: true)\r\n  |> fill(value: 0.0)\r\n  |> max()\r\n  |> keep(columns: [\"_time\", \"_value\", \"character\"])\r\n  |> rename(columns: {_value: \"Max DPS\"})\r\n"
    }
   ]
  }
 ]
}